# Charlottesville Area Trail Profiles

R code

```{r, datain}
library(ggplot2)

trailprofile <- read.csv("trailprofile.csv", header=TRUE, stringsAsFactors=FALSE)
trailprofile <- transform(trailprofile, PainNGain=Elevation/Distance)

p <- ggplot(data=trailprofile, aes(Distance, Elevation, label=Route)) + 
    geom_point(aes(colour=PainNGain, size=PainNGain)) + 
    scale_size(range=c(3,25)) + 
    scale_colour_continuous(low="blue4", high="red2")
p <- p+geom_text(size=5, angle=45, vjust=2, hjust=.1, colour="gray20")
p <- p + scale_x_continuous(limits=c(8, 23))
p <- p + scale_y_continuous(limits=c(700,5200))
p <- p + labs(title="Charlottesville Area Trail Profiles")
```

Table: 

```{r createtable, results='asis', echo=FALSE}
cat("Route | Link | Elevation | Distance | PainNGain", "--- | --- | --- | --- | ---", sep="\n")
cat(apply(trailprofile, 1, function(X) paste(X, collapse=" | ")), sep = "\n")
```

Figure lorem ipsum

```{r, scatterplot, fig.width=11, fig.height=11}
print(p)
```

```{r, debugging, echo=F, eval=F}
# A place to debug without showing up in output file.
str(trailprofile)
p
knit2html("trailprofile.Rmd")

#need to trick github flavored markdown using S for the README.md file
system("cat trailprofile.md | sed 's/```r/```S/g' > README.md")
```
